model: ollama/qwen2.5-coder:32k
model-metadata-file: .aider.model.metadata.json
edit-format: whole
yes-always: true
auto-commits: true
auto-test: true
test-cmd: echo "TODO: Add your build/test command here"
suggest-shell-commands: true
map-tokens: 4096
max-chat-history-tokens: 8192
attribute-author: false
attribute-committer: false
dark-mode: true
